# Generated by Django 5.1 on 2024-08-28 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0002_contact_avatar_alter_contact_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoRecepcionMateriaAlergenos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaentrada', models.DateTimeField(auto_now_add=True)),
                ('materiaprima', models.CharField(max_length=100, verbose_name='Materia Prima')),
                ('loteseprisa', models.CharField(max_length=100, verbose_name='Lotes Seprisa')),
                ('pesobruto', models.CharField(blank=True, max_length=10, null=True)),
                ('pesoneto', models.CharField(blank=True, max_length=10, null=True)),
                ('nocontenedores', models.CharField(blank=True, max_length=10, null=True)),
                ('claveproveedor', models.CharField(blank=True, max_length=10, null=True)),
                ('noanalisis', models.CharField(blank=True, max_length=10, null=True)),
                ('sku', models.CharField(blank=True, max_length=10, null=True)),
                ('noloteproveedor', models.CharField(blank=True, max_length=10, null=True)),
                ('fechacaducidad', models.DateTimeField()),
                ('recibe', models.CharField(max_length=100, verbose_name='Recibe')),
            ],
        ),
        migrations.RemoveField(
            model_name='contact',
            name='avatar',
        ),
    ]
