# Generated by Django 5.1 on 2024-08-30 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_formatorecepcionmateriaalergenos_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoRecepcionMaterialEmpaque',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaentrada', models.DateTimeField(auto_now_add=True)),
                ('material', models.CharField(max_length=100, verbose_name='Material')),
                ('loteseprisa', models.CharField(max_length=100, verbose_name='Lotes Seprisa')),
                ('pesobruto', models.CharField(blank=True, max_length=10, null=True)),
                ('pesoneto', models.CharField(blank=True, max_length=10, null=True)),
                ('nocontenedores', models.CharField(blank=True, max_length=10, null=True)),
                ('claveproveedor', models.CharField(blank=True, max_length=10, null=True)),
                ('noanalisis', models.CharField(blank=True, max_length=10, null=True)),
                ('sku', models.CharField(blank=True, max_length=10, null=True)),
                ('noloteproveedor', models.CharField(blank=True, max_length=10, null=True)),
                ('recibe', models.CharField(max_length=100, verbose_name='Recibe')),
            ],
        ),
        migrations.CreateModel(
            name='FormatoRecepcionMateriaPrima',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fechaentrada', models.DateTimeField(auto_now_add=True)),
                ('materiaprima', models.CharField(max_length=100, verbose_name='Materia Prima')),
                ('loteseprisa', models.CharField(max_length=100, verbose_name='Lotes Seprisa')),
                ('pesobruto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pesoneto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('nocontenedores', models.IntegerField(blank=True, null=True)),
                ('claveproveedor', models.CharField(blank=True, max_length=10, null=True)),
                ('noanalisis', models.CharField(blank=True, max_length=10, null=True)),
                ('sku', models.CharField(blank=True, max_length=10, null=True)),
                ('noloteproveedor', models.CharField(blank=True, max_length=10, null=True)),
                ('fechacaducidad', models.DateTimeField(blank=True, null=True)),
                ('recibe', models.CharField(max_length=100, verbose_name='Recibe')),
            ],
        ),
    ]
