# Generated by Django 5.1 on 2024-08-30 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_formatorecepcionmateriaalergenos_fechacaducidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatorecepcionmateriaprima',
            name='fechacaducidad',
            field=models.DateField(blank=True, null=True),
        ),
    ]
