# Generated by Django 5.1 on 2024-09-13 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_alter_formatorecepcionmateriaprima_fechacaducidad'),
    ]

    operations = [
        migrations.AddField(
            model_name='formatorecepcionmateriaprima',
            name='contenedor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contenedor'),
        ),
        migrations.AddField(
            model_name='formatorecepcionmateriaprima',
            name='de',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='De'),
        ),
        migrations.AddField(
            model_name='formatorecepcionmateriaprima',
            name='realizo',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Realizo'),
        ),
        migrations.AddField(
            model_name='formatorecepcionmateriaprima',
            name='verifico',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Verifico'),
        ),
    ]
