# Generated by Django 5.1 on 2024-09-18 16:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0007_formatorecepcionmateriaprima_contenedor_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='EtiquetaCuarentena',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(blank=True, max_length=100, null=True, verbose_name='Nombre')),
                ('firma', models.CharField(blank=True, max_length=100, null=True, verbose_name='Firma')),
                ('noanalisis', models.CharField(blank=True, max_length=100, null=True, verbose_name='No. Analisis')),
            ],
        ),
        migrations.CreateModel(
            name='FormatoSolicitudAnalisis',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materiaprima', models.CharField(max_length=100, verbose_name='Materia Prima')),
                ('productoterminado', models.CharField(max_length=100, verbose_name='Prodcuto Terminado')),
                ('materialempaque', models.CharField(max_length=100, verbose_name='Material de Empaque')),
                ('noanálisis', models.CharField(max_length=100, verbose_name='No. Analisis')),
                ('fechahoraentrada', models.DateField(blank=True, null=True)),
                ('nolote', models.CharField(max_length=100, verbose_name='No. Lote')),
                ('cantidadrecibida', models.CharField(max_length=100, verbose_name='Cantidad Recibida')),
                ('nocontenedores', models.CharField(max_length=100, verbose_name='No. Contenedores')),
                ('producto', models.CharField(max_length=100, verbose_name='Producto')),
                ('solicitante', models.CharField(max_length=100, verbose_name='Solicitante')),
                ('recibe', models.CharField(max_length=100, verbose_name='Recibe')),
                ('muestreo', models.CharField(max_length=100, verbose_name='Muetreo')),
                ('fechahoramuestreo', models.CharField(max_length=100, verbose_name='Fecha y hora de muestreo')),
                ('observaciones', models.CharField(max_length=100, verbose_name='Observaciones')),
                ('analista', models.CharField(max_length=100, verbose_name='Analista')),
                ('fechahoradictamen', models.DateField(blank=True, null=True)),
                ('dictamen', models.CharField(max_length=100, verbose_name='Dictamen')),
                ('observacioness', models.CharField(max_length=100, verbose_name='Observaciones')),
                ('fechahoraentrega', models.DateField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='KardexRecepcionMateriaPrimaAlmacen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('materiaprima', models.CharField(blank=True, max_length=100, null=True, verbose_name='Materia Prima')),
                ('fechacaducidad', models.DateField(blank=True, null=True)),
                ('fechaentrada', models.DateField(blank=True, null=True)),
                ('codigoproveedorcliente', models.CharField(blank=True, max_length=100, null=True, verbose_name='Codigo Proveedor o Cliente')),
                ('noloteseprisa', models.CharField(blank=True, max_length=100, null=True, verbose_name='No. Lote Seprisa')),
                ('cantidadneto', models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Cantidad Neto')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU')),
                ('fechasalida', models.DateField(blank=True, null=True)),
                ('clienteusointerno', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cliente Uso Interno')),
                ('noloteproveedor', models.CharField(blank=True, max_length=100, null=True, verbose_name='No. LOte Proveedor')),
                ('cantidadsale', models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Cantidad Sale')),
                ('cantidadqueda', models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Cantidad Queda')),
                ('realizo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Realizo')),
                ('observaciones', models.CharField(blank=True, max_length=255, null=True, verbose_name='Observaciones')),
            ],
        ),
        migrations.RemoveField(
            model_name='formatorecepcionmateriaprima',
            name='contenedor',
        ),
        migrations.RemoveField(
            model_name='formatorecepcionmateriaprima',
            name='de',
        ),
        migrations.RemoveField(
            model_name='formatorecepcionmateriaprima',
            name='realizo',
        ),
        migrations.RemoveField(
            model_name='formatorecepcionmateriaprima',
            name='verifico',
        ),
        migrations.CreateModel(
            name='EtiquetaIdentificacionMateriales',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('material', models.CharField(blank=True, max_length=100, null=True, verbose_name='Material')),
                ('noanalisis', models.CharField(blank=True, max_length=100, null=True, verbose_name='No Analisis')),
                ('proveedorclientesku', models.CharField(blank=True, max_length=100, null=True, verbose_name='Proveedor o Cliente SKU')),
                ('noloteproveedor', models.CharField(blank=True, max_length=100, null=True, verbose_name='No Lote Proveedor')),
                ('noloteinterno', models.CharField(blank=True, max_length=100, null=True, verbose_name='No Lote Interno')),
                ('pbruto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ptara', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('pneto', models.CharField(blank=True, max_length=100, null=True, verbose_name='P. Neto')),
                ('sku', models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU')),
                ('contenedor', models.CharField(blank=True, max_length=100, verbose_name='Contenedor')),
                ('de', models.CharField(blank=True, max_length=100, null=True, verbose_name='De')),
                ('realizo', models.CharField(blank=True, max_length=100, null=True, verbose_name='Realizo')),
                ('verifico', models.CharField(blank=True, max_length=100, null=True, verbose_name='Verifico')),
                ('formato_recepcion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='etiquetas', to='contacts.formatorecepcionmateriaprima')),
            ],
        ),
    ]
