# Generated by Django 5.1 on 2024-09-18 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0008_etiquetacuarentena_formatosolicitudanalisis_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formatorecepcionmateriaprima',
            old_name='pesoneto',
            new_name='pesotara',
        ),
    ]
