# Generated by Django 5.1 on 2024-09-18 17:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0009_rename_pesoneto_formatorecepcionmateriaprima_pesotara'),
    ]

    operations = [
        migrations.RenameField(
            model_name='formatorecepcionmateriaprima',
            old_name='pesotara',
            new_name='pesoneto',
        ),
    ]
