# Generated by Django 5.1 on 2024-09-23 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0010_rename_pesotara_formatorecepcionmateriaprima_pesoneto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='etiquetaidentificacionmateriales',
            name='formato_recepcion',
        ),
        migrations.AlterField(
            model_name='etiquetaidentificacionmateriales',
            name='material',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.formatorecepcionmateriaprima'),
        ),
    ]
