# Generated by Django 5.1 on 2024-09-23 19:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0011_remove_etiquetaidentificacionmateriales_formato_recepcion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='etiquetaidentificacionmateriales',
            name='formato_recepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.formatorecepcionmateriaprima'),
        ),
        migrations.AlterField(
            model_name='etiquetaidentificacionmateriales',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Material'),
        ),
    ]
