# Generated by Django 5.1 on 2024-10-02 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0012_etiquetaidentificacionmateriales_formato_recepcion_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrdenProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('producto', models.CharField(blank=True, max_length=100, null=True, verbose_name='Producto')),
                ('claveskumaquila', models.CharField(blank=True, max_length=100, null=True, verbose_name='CLAVE/SKU Maquila')),
                ('presentacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Presentacion')),
                ('noordenproduccion', models.CharField(blank=True, max_length=100, null=True, verbose_name='No. Orden Produccion')),
                ('numerolote', models.CharField(blank=True, max_length=100, null=True, verbose_name='Numero de lote')),
                ('fechacaducidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fecha de caducidad')),
                ('fechainicioproceso', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fecha Inicio Proceso')),
                ('fechaterminoproceso', models.CharField(blank=True, max_length=100, null=True, verbose_name='Fecha Termino de Proceso')),
                ('rendimientoteorico', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rendimiento teorico')),
                ('rendimientoreal', models.CharField(blank=True, max_length=100, null=True, verbose_name='Rendimiento real')),
                ('skump', models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU MP')),
                ('material', models.CharField(blank=True, max_length=100, null=True, verbose_name='Material')),
                ('nolote', models.CharField(blank=True, max_length=100, null=True, verbose_name='No. Lpte')),
                ('unidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Unidad')),
                ('cantidad', models.CharField(blank=True, max_length=100, null=True, verbose_name='Cantidad')),
                ('surtio', models.CharField(blank=True, max_length=100, null=True, verbose_name='Surtió')),
                ('verifico', models.CharField(blank=True, max_length=100, null=True, verbose_name='Verificó')),
                ('observaciones', models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones')),
            ],
        ),
        migrations.AlterField(
            model_name='kardexrecepcionmateriaprimaalmacen',
            name='noloteproveedor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='No. Lote Proveedor'),
        ),
    ]
