# Generated by Django 5.1 on 2024-10-03 17:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0014_remove_ordenproduccion_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenproduccion',
            name='noordenproduccion',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='No Orden de Produccion'),
        ),
    ]
