# Generated by Django 5.1 on 2024-10-03 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0015_alter_ordenproduccion_noordenproduccion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ordenproduccion',
            name='noordenproduccion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='No Orden de Produccion'),
        ),
    ]
