# Generated by Django 5.1 on 2024-10-03 19:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0017_rename_noordenproduccion_ordenproduccion_nordenproduccion_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ordenproduccion',
            old_name='nordenproduccion',
            new_name='noordenproduccion',
        ),
    ]
