# Generated by Django 5.1 on 2024-10-03 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0018_rename_nordenproduccion_ordenproduccion_noordenproduccion'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordenproduccion',
            name='cantidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='nolote',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='No. Lpte'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='observaciones',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='skump',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU MP'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='surtio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Surtió'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='unidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='verifico',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Verificó'),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='noordenproduccion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='No. Orden Produccion'),
        ),
    ]
