# Generated by Django 5.1 on 2024-10-03 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0019_ordenproduccion_cantidad_ordenproduccion_material_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenproduccion',
            name='cantidad',
        ),
        migrations.RemoveField(
            model_name='ordenproduccion',
            name='material',
        ),
        migrations.RemoveField(
            model_name='ordenproduccion',
            name='nolote',
        ),
        migrations.RemoveField(
            model_name='ordenproduccion',
            name='observaciones',
        ),
        migrations.RemoveField(
            model_name='ordenproduccion',
            name='skump',
        ),
        migrations.RemoveField(
            model_name='ordenproduccion',
            name='surtio',
        ),
        migrations.RemoveField(
            model_name='ordenproduccion',
            name='unidad',
        ),
        migrations.RemoveField(
            model_name='ordenproduccion',
            name='verifico',
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='noordenproduccion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='No Orden de Produccion'),
        ),
    ]
