# Generated by Django 5.1 on 2024-10-03 19:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0020_remove_ordenproduccion_cantidad_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='detalleorden',
            name='orden',
        ),
    ]
