# Generated by Django 5.1 on 2024-10-03 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0021_remove_detalleorden_orden'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DetalleOrden',
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='cantidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Cantidad'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='material',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Material'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='nolote',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='No. Lpte'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='observaciones',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Observaciones'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='skump',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='SKU MP'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='surtio',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Surtió'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='unidad',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Unidad'),
        ),
        migrations.AddField(
            model_name='ordenproduccion',
            name='verifico',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Verificó'),
        ),
        migrations.AlterField(
            model_name='kardexrecepcionmateriaprimaalmacen',
            name='cantidadneto',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Cantidad Neto'),
        ),
        migrations.AlterField(
            model_name='kardexrecepcionmateriaprimaalmacen',
            name='cantidadqueda',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Cantidad Queda'),
        ),
        migrations.AlterField(
            model_name='kardexrecepcionmateriaprimaalmacen',
            name='cantidadsale',
            field=models.IntegerField(blank=True, max_length=100, null=True, verbose_name='Cantidad Sale'),
        ),
        migrations.AlterField(
            model_name='ordenproduccion',
            name='noordenproduccion',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='No. Orden Produccion'),
        ),
    ]
