# Generated by Django 5.1 on 2024-10-03 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0022_delete_detalleorden_ordenproduccion_cantidad_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kardexrecepcionmateriaprimaalmacen',
            name='cantidadneto',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad Neto'),
        ),
        migrations.AlterField(
            model_name='kardexrecepcionmateriaprimaalmacen',
            name='cantidadqueda',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad Queda'),
        ),
        migrations.AlterField(
            model_name='kardexrecepcionmateriaprimaalmacen',
            name='cantidadsale',
            field=models.IntegerField(blank=True, null=True, verbose_name='Cantidad Sale'),
        ),
    ]
