# Generated by Django 5.1 on 2024-10-03 19:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0023_alter_kardexrecepcionmateriaprimaalmacen_cantidadneto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ordenproduccion',
            name='noordenproduccion',
        ),
    ]
