# Generated by Django 5.1 on 2024-11-11 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0025_remove_ordenproduccion_cantidad_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormatoBitacoraProductoTerminado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presentacion', models.CharField(blank=True, max_length=100, null=True, verbose_name='Presentacion')),
                ('contenedores', models.IntegerField(blank=True, null=True)),
                ('cliente', models.CharField(blank=True, max_length=10, null=True)),
                ('recibe', models.CharField(blank=True, max_length=10, null=True)),
                ('observaciones', models.TextField(blank=True, null=True)),
                ('fechacaducidad', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras_fechacaducidad', to='contacts.formatorecepcionmateriaprima')),
                ('fechaentrada', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras_entrada', to='contacts.formatorecepcionmateriaprima')),
                ('lote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras_lote', to='contacts.formatorecepcionmateriaprima')),
                ('noanalisis', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras_noanalisis', to='contacts.formatorecepcionmateriaprima')),
                ('producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras_producto', to='contacts.formatorecepcionmateriaprima')),
                ('sku', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bitacoras_sku', to='contacts.formatorecepcionmateriaprima')),
            ],
        ),
    ]
