# Generated by Django 5.1 on 2024-11-12 17:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0026_formatobitacoraproductoterminado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formatobitacoraproductoterminado',
            name='fechacaducidad',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formatobitacoraproductoterminado',
            name='fechaentrada',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formatobitacoraproductoterminado',
            name='lote',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Lotes Seprisa'),
        ),
        migrations.AlterField(
            model_name='formatobitacoraproductoterminado',
            name='noanalisis',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='formatobitacoraproductoterminado',
            name='observaciones',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='formatobitacoraproductoterminado',
            name='producto',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Materia Prima'),
        ),
        migrations.AlterField(
            model_name='formatobitacoraproductoterminado',
            name='sku',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='sku'),
        ),
        migrations.AlterField(
            model_name='kardexrecepcionmateriaprimaalmacen',
            name='cantidadneto',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kardex_cantidadneto', to='contacts.formatorecepcionmateriaprima'),
        ),
        migrations.AlterField(
            model_name='kardexrecepcionmateriaprimaalmacen',
            name='codigoproveedorcliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kardex_codigoproveedorcliente', to='contacts.formatorecepcionmateriaprima'),
        ),
        migrations.AlterField(
            model_name='kardexrecepcionmateriaprimaalmacen',
            name='fechacaducidad',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kardex_fechacaducidad', to='contacts.formatorecepcionmateriaprima'),
        ),
        migrations.AlterField(
            model_name='kardexrecepcionmateriaprimaalmacen',
            name='fechaentrada',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kardex_fechaentrada', to='contacts.formatorecepcionmateriaprima'),
        ),
        migrations.AlterField(
            model_name='kardexrecepcionmateriaprimaalmacen',
            name='materiaprima',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kardex_materiaprima', to='contacts.formatorecepcionmateriaprima'),
        ),
        migrations.AlterField(
            model_name='kardexrecepcionmateriaprimaalmacen',
            name='noloteseprisa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kardex_noloteseprisa', to='contacts.formatorecepcionmateriaprima'),
        ),
        migrations.AlterField(
            model_name='kardexrecepcionmateriaprimaalmacen',
            name='sku',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='kardex_sku', to='contacts.formatorecepcionmateriaprima'),
        ),
    ]
