# Generated by Django 5.1 on 2024-11-13 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0027_alter_formatobitacoraproductoterminado_fechacaducidad_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='kardexrecepcionmateriaprimaalmacen',
            name='formato_recepcion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='contacts.formatorecepcionmateriaprima'),
        ),
        migrations.AlterField(
            model_name='etiquetaidentificacionmateriales',
            name='contenedor',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Contenedor'),
        ),
    ]
