from django.urls import path

from contacts import views

from .views import tu_vista_guardar, buscar_etiqueta_identificacion_materiales, buscar_orden_produccion, buscar_material,buscar_kardex

urlpatterns = [
    path('list', views.ContactListView.as_view(),name='contact_list'),
    path('new/', views.ContactCreateView.as_view(),name='contact_new'),
    path('<int:pk>/edit/', views.ContactUpdateView.as_view(),name='contact_edit'),
    path('<int:pk>/delete/', views.ContactDeleteView.as_view(),name='contact_delete'),
    path(" ", views.Menu.as_view(),name='Menu'),
    path("fomatorecepcionmateria/", views.FormatoRecepcionMateriaAlergenosView.as_view(),name='formato_recepcion_materia'),
    path("formatorecepcionmateriaalergenos/", views.FormatoRecepcionMateriaAlergenosListView.as_view(),name='formatorecepcionmateriaalergenos_list'),
    path("formatorecepcionmaterialempaque/", views.FormatoRecepcionMaterialEmpaqueView.as_view(),name='formato_recepcion_material_empaque'),
    path("formarorecepcionmaterialempaquelist/",views.FormatoRecepcionMaterialEmpaqueListView.as_view(),name='formatorecepcionmaterialempaque_list'),
    path('formatorecepcionmateriaprima/',views.FormatoRecepcionMateriaPrimaListView.as_view(),name='formato_recepcion_materia_prima'),
    path('formatorecepcionmateriaprima/new/', views.FormatoRecepcionMateriaPrimaCreateView.as_view(),name='formatorecepcionmateriaprima_new'),
    path('formatorecepcionmateriaprima/<int:pk>/edit/',views.FormatoRecepcionMateriaPrimaUpdateView.as_view(),name='formatorecepcionmateriaprima_edit'),
    path('formatorecepcionmateriaprima/<int:pk>/delete/',views.FormatoRecepcionMateriaPrimaDeleteView.as_view(),name='formatorecepcionmateriaprima_delete'),
    path("login/", views.LoginView.as_view(), name='login'),
    path('etiq/', views.etiquetas.as_view(), name='etiquetas'),
    path('buscar/', buscar_etiqueta_identificacion_materiales, name='buscar_etiqueta'),
    path('guardar/', views.GuardarEtiquetaView.as_view(), name='guardar_etiqueta'),
    path('etiquetalist', views.EtiquetaIdentificacionMaterialesListView.as_view(),name='etiqueta_identificacion_materiales_list'),
    path('guardar/', tu_vista_guardar, name='tu_vista_guardar'),
    path('orden/', views.orden_produccion.as_view(), name='orden_produccion'),
    path('orden2/', views.orden_produccion2.as_view(),name='orden_produccion2'),
    path('exportordenproduccion/pdf/', views.export_orden_produccion_pdf, name='export_orden_produccion_pdf'),
    path('exportordenproduccion2/pdf/', views.export_orden_produccion2_pdf, name='export_orden_produccion2_pdf'),
    path('etiquetacuarentena', views.Etiqueta_cuarentena.as_view(), name='etiqueta_cuarentena'),
    path('kardex/', views.kardex.as_view(), name='kardex'),
    path('kardex/pdf/', views.export_kardex_pdf, name='export_kardex_pdf'),
    path('kardex/list/',views.KardexListView.as_view(),name='kardex_list'),
    path('kardex/new/', views.KardexCreateView.as_view(),name='kardex_new'),
    path('kardex/<int:pk>/edit/',views.KardexUpdateView.as_view(),name='kardex_edit'),
    path('kardex/<int:pk>/delete/',views.KardexDeleteView.as_view(),name='kardex_delete'),
    path('kardex/buscar/', buscar_kardex, name='buscar_kardex'),
    path('kardex/guardar/', views.GuardarKardexView.as_view(), name='guardar_kardex'),
    path('export/pdf/', views.export_contacts_pdf, name='export_contacts_pdf'),
    path('exportformatorecepcionmateriaprima/pdf/', views.export_formato_recepcion_materia_prima_pdf, name='export_formato_recepcion_msteria_prima_pdf'),
    path('exportetiquetaidentificacionmateriales/pdf', views.export_etiqueta_identificacion_materiales_pdf, name='export_etiqueta_identificacion_materiales_pdf'),
    path('exportetiquetacuarentena/pdf', views.export_etiqueta_cuarentena_pdf, name='export_etiqueta_cuarentena_pdf'),
    path('exportformatosolicitudanalisis/pdf', views.export_formato_solicitud_analisis_pdf, name='export_formato_solicitud_analisis_pdf'),
    path('formatosolicitudanalisis/', views.FormatoSolicitudAnalisisView.as_view(), name='formato_solicitud_analisis'),
    path('exportformatosolicitudanalisis/pdf/', views.export_formato_solicitud_analisis_pdf, name='export_formato_solicitud_analisis_pdf'),
    path('materiaprima/details/', views.get_materia_prima_details, name='get_materia_prima_details'),
    path('buscar_solicitud_analisis/', views.buscar_solicitud_analisis, name='buscar_solicitud_analisis'),
    path('ordenproduccionview/', views.OrdenProduccionView.as_view(), name='orden_produccion_view'),
    path('ordenproduccion/list', views.OrdenProduccionListView.as_view(),name='ordenproduccion_list'),
    path('ordenproduccion/new/', views.OrdenProduccionCreateView.as_view(),name='ordenproduccion_new'),
    path('ordenproduccionlist/new/', views.OrdenProduccionCreateListView.as_view(),name='ordenproduccion_newlist'),
    path('ordenproduccionlist/<int:pk>/edit/', views.OrdenProduccionUpdateView.as_view(),name='ordenproduccion_edit'),
    path('ordenproduccionlist/<int:pk>/delete/', views.OrdenProduccionDeleteView.as_view(),name='ordenproduccion_delete'),
    path('buscar-orden/', buscar_orden_produccion, name='buscar_orden_produccion'),
    path('buscar-material/', buscar_material, name='buscar_material'),
    path('controlaseguramientoview/', views.ControlAseguramientoView.as_view(), name='control_aseguramiento_view'),
    path('controlaseguramientopdf/pdf/', views.export_control_aseguramiento_pdf, name='export_control_aseguramiento_pdf'),
    path('controlaseguramientopdf2/pdf/', views.export_control_aseguramiento2_pdf, name='export_control_aseguramiento_pdf2'),
    path('menupview/', views.MenuPView.as_view(), name='menu_p_view'),
    path('menuprview/', views.MenuPrView.as_view(), name='menu_pr_view'),
    path('bitacoraproductoterminadoview/', views.FormatoBitacoraProductoTerminadoView.as_view(), name='bitacora_producto_terminado_view'),
    path('bitacoraproductoterminadopdf/pdf/', views.export_bitacora_producto_terminado_pdf, name='export_bitacora_producto_terminado_pdf'),
    path('bitacoraproductoterminado/',views.FormatoBitacoraProductoTerminadoListView.as_view(),name='formato_bitacora_producto_terminado'),
    path('bitacoraproductoterminado/new/', views.FormatoBitacoraProductoTerminadoCreateView.as_view(),name='formatobitacoraproductoterminado_new'),
    path('bitacoraproductoterminado/<int:pk>/edit/',views.FormatoBitacoraProductoTerminadoUpdateView.as_view(),name='formatobitacoraproductoterminado_edit'),
    path('bitacoraproductoterminado/<int:pk>/delete/',views.FormatoBitacoraProductoTerminadoDeleteView.as_view(),name='formatobitacoraproductoterminado_delete'),

]
